### ISSUE TITLE
Test classes for Windows and Linux have wrong name

### ISSUE THREAD

**Issue by hococoder** [jzy3d/vtk-java-natives#8]
The test files for both Win64 and Linux are both named "TestVtkNativeLibrariesImplMacOS_x86_64.java".  This should be fixed to reflect the actual platform.

**Comment by jzy3d** [comment]
Thanks, and sorry for missing your ticket (do not hesitate to notify me through annotations @hococoder). This has been fixed in the mean time.
Is everything working fine on your side to deliver your custom VTK distro?
